version: "3.9"
services:
  app:
    image: node:20
    working_dir: /app
    command: sh -lc "rm -rf .next && npm ci && npm run build && npm run start"
    environment:
      NODE_ENV: production
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-change-me-strong}
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      ACME_AGREE: "true"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:

