version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-change-me-strong}
      PORT: 3000
    user: "1000"
    volumes:
      - ./data:/app/data
      - ./public:/app/public
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./public:/public # Caddy needs access to the public directory
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: